PPWGroupProject/urls.py
from django.contrib import admin
from django.urls import path, include
from support import views as support
from feedback import views as feedback_views
from kuesioner import views as kuesioner
from articles import views as articles
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('duar.urls')),
    path('formulirsupport/', support.formulir_support, name = 'formulirsupport'),
    path('landingsupport/', support.landingsupport, name = 'landingsupport'),

    path('articles/', articles.articles_page, name = 'articles'),
    path('insertarticles/', articles.insert_articles, name = 'insertarticles'),
    path('articles/<str:pk>', articles.selengkapnya, name = 'selengkapnya'),
    path('deletearticle/<str:pk>', articles.hapus_artikel, name = 'hapus_artikel'),

    path('feedback/', feedback_views.feedback, name = 'feedback'),

    path('kuesioner/', kuesioner.formulir_kuesioner, name = 'kuesioner'),
    path('listkuesioner/', kuesioner.list_kuesioner, name = 'listkuesioner'),
    path('hasilkuesioner/<str:pk>/', kuesioner.hasil_kuesioner, name = 'hasilkuesioner'),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

duar/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact')
]

feedback/models.py
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey

class Feedback(MPTTModel):
	user = models.CharField(max_length=35, default='anonymous')
	created = models.DateTimeField(auto_now_add=True)
	body = models.TextField()
	parent = TreeForeignKey('self', null=True, blank=True, on_delete=models.CASCADE, related_name='children')

	class MPTTMeta :
		order_insertion_by = ['created']

	def __str__(self):
		return f'Feedback by {self.user}'

feedback/forms.py
from django import forms
from .models import Feedback
from mptt.forms import TreeNodeChoiceField

class FeedbackForm(forms.ModelForm):
	parent = TreeNodeChoiceField(queryset=Feedback.objects.all())
	def __init__(self, *args, **kwargs):
		super().__init__(*args,**kwargs)
		self.fields['parent'].widget.attrs.update({'class':'d-none'})
		self.fields['parent'].label=''
		self.fields['parent'].required = False

	class Meta:
		model = Feedback
		fields = ('user','parent','body')
		widgets = {
				'user':forms.TextInput(attrs={'class':'form-control','placeholder':'Your name'}),
				'body':forms.Textarea(attrs={'class':'form-control', 'placeholder':'Type Your Feedback'})
		}

feedback/views.py
from django.shortcuts import render, HttpResponseRedirect
from .models import Feedback
from .forms import FeedbackForm
# Create your views here.
def feedback(request):
	feedback = Feedback.objects.all()
	feedForm = FeedbackForm()
	context = {
		'feedbacks':feedback,
		'form':feedForm,
	}
	if request.method == "POST":
		feedForm = FeedbackForm(request.POST)
		if feedForm.is_valid():
			feedForm.save()
			return HttpResponseRedirect('/feedback')
	else:
		feedform = FeedbackForm()
	return render (request, 'feedback.html',context)

feedback/templates/base_feedback.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

     <!-- Logo -->
    <link rel="icon" href="{% static 'image/logo.svg' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- My CSS-->
    <link rel="stylesheet" href="{% static 'css/feedback.css' %}">

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

    <!-- Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Fengyuan Chen's Datepicker -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css" integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js" integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k=" crossorigin="anonymous"></script>

    <title>Feedback</title>
</head>
<body>
    <nav class="navbar navbar-expand-xl navbar-light bg-transparent">
        <a class="navbar-brand" href="{% url 'index' %}">DUAR</a>
        <button class="navbar-dark navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
          <span class="navbar-dark navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'kuesioner' %}">Assesment</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url "articles" %}">Articles</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'formulirsupport' %}">Support</a>
              </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url "feedback" %}">Feedback</a>
              </li>
             <li class="nav-item">
                <a class="nav-link" href="{% url "contact" %}">Contact</a>
              </li>
          </ul>
        </div>
      </nav>
    {% block content %}
    {% endblock %}
<script>
  function myFunction(id){
    if(document.contains(document.getElementById("newform"))){
      document.getElementById("newform").remove();
    }
    var a = document.getElementById(id);
    a.insertAdjacentHTML('afterend',
      '<form id="newform" class="form-insert py-2" method="post" autocomplete="off"> \
      <div><h2>Reply:</h2></div> \
      <label for="id_user">Name:</label> \
      <input type="text" name="user" class="form-control" maxlength="35" id="id_user" placeholder="Your Name" required="true">\
      <select name="parent" class="d-none" id="id_parent"> \
      <option value=" ' + id + '" selected=" ' + id + '"></option> \
      </select> \
      <br> \
      <label for="id_body">Feedback:</label> \
      <textarea name="body" class="form-control" required="true" id="id_body" placeholder="Type your reply"></textarea> \
      {% csrf_token %} \
      <br> \
      <button class="btn btn-primary btn-md" type="submit">Submit</button> \
      </form>'
      );
  }
  $('#myform').trigger("reset");
</script>

</body>
</html>

feedback/templates/feedback.html
{% extends 'base_feedback.html' %}
{% block content %}
       <div class="text text-center text-light">
          <h2>Help Us Improve</h2>
          <h3>Post Your Feedback</h3>
       </div>
       {% load mptt_tags %}
       <div class="container">
        {% recursetree feedbacks %}
        <div class="jumbotron">
            <div class="row" id="{{ node.id }}">
              <div class="col">{{ node.user }}</div>
              <div class="col">{{ node.created }}</div>
            </div>
            <div>{{ node.body }} </div>
           
            <hr>
            <button class="button" onclick="myFunction({{ node.id }})">Reply</button>
        </div>
        {% if not node.is_leaf_node %}
        <div class="children pl-2 pl-md-5">
          {{ children }}
        </div>
        {% endif %}
        {% endrecursetree %}
        
       </div>
       <div id="containerfeedform" class="container mt-5">
        <h3>Post a New Feedback</h3>
         <form id="myform" class="form-group" method="post" autocomplete="off">
          <label>Name:</label>
           {{ form.user }}
          <br>
          <label>Feedback:</label>
            {{ form.body }}
            {% csrf_token %}
           <br>
           <button class="btn btn-primary btn-lg" type="submit">Submit</button>
         </form>
       </div>
{% endblock %}