PPWGroupProject/urls.py
from django.contrib import admin
from django.urls import path, include
from support import views as support
from feedback import views as feedback_views
from kuesioner import views as kuesioner
from articles import views as articles
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('duar.urls')),
    path('formulirsupport/', support.formulir_support, name = 'formulirsupport'),
    path('landingsupport/', support.landingsupport, name = 'landingsupport'),

    path('articles/', articles.articles_page, name = 'articles'),
    path('insertarticles/', articles.insert_articles, name = 'insertarticles'),
    path('articles/<str:pk>', articles.selengkapnya, name = 'selengkapnya'),
    path('deletearticle/<str:pk>', articles.hapus_artikel, name = 'hapus_artikel'),

    path('feedback/', feedback_views.feedback, name = 'feedback'),

    path('kuesioner/', kuesioner.formulir_kuesioner, name = 'kuesioner'),
    path('listkuesioner/', kuesioner.list_kuesioner, name = 'listkuesioner'),
    path('hasilkuesioner/<str:pk>/', kuesioner.hasil_kuesioner, name = 'hasilkuesioner'),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

articles/urls.py
from django.urls import path

from . import views

app_name = 'articles'

urlpatterns = [
]

duar/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact')
]

articles/models.py
import datetime
from django.db import models

KATEGORI_CHOICES = (
    ('Umum', 'Umum'),
    ('Kesehatan', 'Kesehatan'),
    ('Teknologi', 'Teknologi'),
    ('Politik', 'Politik'),
    ('Ekonomi', 'Ekonomi'),
    ('Sosial', 'Sosial'),
    ('Pendidikan', 'Pendidikan'),
    ('Makanan', 'Makanan'),
    ('Alam', 'Alam'),
)

# Create your models here.
class Articles(models.Model):
    penulis = models.CharField(max_length=20, null=True)
    kategori = models.CharField(max_length=20, choices=KATEGORI_CHOICES, default='Umum')
    tanggal = models.DateField()
    judul = models.CharField(max_length=100)
    isi_artikel = models.TextField(max_length=1000)
    gambar_artikel = models.ImageField(default="virusbiru2.svg")

    def __str__(self):
        return self.judul

articles/forms.py
from django import forms
from django.forms import ModelForm, Textarea, TextInput, DateInput
from .models import Articles
from crispy_forms.helper import FormHelper
from django.contrib.admin.widgets import AdminDateWidget


KATEGORI_CHOICES = (
    ('Umum', 'Umum'),
    ('Kesehatan', 'Kesehatan'),
    ('Teknologi', 'Teknologi'),
    ('Politik', 'Politik'),
    ('Ekonomi', 'Ekonomi'),
    ('Sosial', 'Sosial'),
    ('Pendidikan', 'Pendidikan'),
    ('Makanan', 'Makanan'),
    ('Alam', 'Alam'),
)

class ArticlesForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(ArticlesForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.fields['penulis'].label = 'Penulis'
        self.fields['kategori'].label = 'Kategori'
        self.fields['tanggal'].label = 'Tanggal'
        self.fields['judul'].label = 'Judul'
        self.fields['isi_artikel'] = forms.CharField(widget=forms.Textarea, min_length=300, max_length=1000)
        self.fields['isi_artikel'].label = 'Isi Artikel'
        self.fields['gambar_artikel'].label = 'Gambar Artikel'

    class Meta:
        model = Articles
        fields = '__all__'

articles/views.py
from django.shortcuts import render, redirect
from .models import Articles
from .forms import ArticlesForm
from django.http import HttpResponse


# Create your views here.
def articles_page(request):
    semua_artikel = Articles.objects.all()
    jumlah_semua_artikel = semua_artikel.count()
    context = {'semua_artikel': semua_artikel, 'jumlah_semua_artikel': jumlah_semua_artikel}
    return render(request, 'articles.html', context)

def insert_articles(request):
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = ArticlesForm(request.POST, request.FILES)
        # check whether it's valid:
        if form.is_valid():
            form.save()
            return redirect('articles')
        # if a GET (or any other method) we'll create a blank form
    else:
        form = ArticlesForm()
    return render(request, 'insertarticles.html', {'form': form})

def selengkapnya(request, pk):
    satu_artikel = Articles.objects.get(id = pk)
    return render(request, 'selengkapnya.html', {'satu_artikel': satu_artikel})

def hapus_artikel(request, pk):
    satu_artikel = Articles.objects.get(id=pk)
    if request.method == "POST":
        satu_artikel.delete()
        return redirect("articles")
    context = {'satu_artikel': satu_artikel}
    return render(request, 'konfirmhapus.html', context)

articles/templates/articles.html
{% extends 'base_articles.html' %}
{% load static %}
{% block cdnscript %}
{% endblock %}
{% block content %}
    <header class="container_judul">
        <h1 class="landing_judul">
            Semua Artikel
        </h1>
        <a href="{% url 'insertarticles' %}">
            <img src="{% static 'image/plus 2.svg' %}" class="plus" alt="">
        </a>
    </header>

    <section class="container_articles">
        {% for artikel in semua_artikel  %}
        <div class="single_artikel">
            <div class="container_gambar">
                <img class = "gambar_artikel" src= "{{ artikel.gambar_artikel.url }}" alt="">
            </div>
            <div class="isi_artikel">
                <p class="judul_artikel">
                    {{ artikel.judul }}
                </p>
                <p class="isi_artikel">
                    {{ artikel.isi_artikel|truncatechars:180 }}
                </p>
            </div>

            <div class="hapus_dan_lanjutan">
                <form action="{% url 'selengkapnya' artikel.id %}" method="post">
                         {% csrf_token %}
                    <button type="submit" class="btn btn-info" id="btnselengkapnya">Selengkapnya</button>
                </form>
                <a href="{% url 'hapus_artikel' artikel.id %}"><button type="button" class="btn btn-danger" id="btnHapusmain">Hapus Artikel</button></a>
            </div>
            <div class="tanggal_kategori">
                  <p class="kategori">
                    Oleh <span style="color:red;"> {{ artikel.penulis }}</span>
                </p>
                <p class="tanggal_main">
                     🕐 {{ artikel.tanggal}}
                </p>
            </div>

        </div>
        {% endfor %}
    {% if jumlah_semua_artikel == 0 %}
        <h1 class="tidak_ada_artikel">
            Wah belum ada artikel nih, tekan tombol + untuk menambahkan artikel...
        </h1>
    {% endif %}
    </section>
{% endblock %}

articles/templates/base_articles.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

     <!-- Logo -->
    <link rel="icon" href="{% static "image/logo.svg" %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- My CSS-->
    <link rel="stylesheet" href="{% static 'css/articles.css' %}">

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

    <!-- Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Fengyuan Chen's Datepicker -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css" integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js" integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k=" crossorigin="anonymous"></script>

    <title>Articles</title>
</head>
<body>
    <nav class="navbar navbar-expand-xl navbar-light bg-transparent">
        <a class="navbar-brand" href="#">DUAR</a>
        <button class="navbar-dark navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
          <span class="navbar-dark navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'kuesioner' %}">Assesment</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url "articles" %}">Articles</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'formulirsupport' %}">Support</a>
              </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url "feedback" %}">Feedback</a>
              </li>
             <li class="nav-item">
                <a class="nav-link" href="{% url "contact" %}">Contact</a>
              </li>
          </ul>
        </div>
      </nav>
    {% block content %}
    {% endblock %}
</body>
</html>

articles/templates/insertarticles.html
{% extends "base_articles.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
    <header class="container_judul">
        <h1 class="landing_judul">
            Tambahkan Artikel
        </h1>
    </header>
    <section class="container_form">
        <form action="" method="post" enctype="multipart/form-data" id="formUtama">
              {% csrf_token %}
              {{ form|crispy }}
             <input type="submit" value="Submit" class="btn btn-primary" id="submitButton" />
        </form>
    </section>

    <script>
    $(function () {
      $("#id_tanggal").datepicker({
      format:'yyyy-mm-dd',
    });
  });
  </script>
{% endblock %}

articles/templates/konfirmhapus.html
{% extends 'base_articles.html' %}
{% block content %}

<header class="container_judul">
        <h1 class="landing_judul">
            Apakah anda yakin ingin menghapus artikel ini?
        </h1>
</header>

<section class="container_konfirmasi">
     <a href="{% url 'articles' %}"><button type="button" class="btn btn-info btn-lg" id="btntidak">Tidak</button></a>
    <form action="{% url 'hapus_artikel' satu_artikel.id %}" method="POST">
                {% csrf_token %}
            <button type="submit" class="btn btn-danger btn-lg" id="btnyakin" >Yakin</button>
    </form>
</section>

{% endblock %}

articles/templates/selengkapnya.html
{% extends 'base_articles.html' %}
{% load static %}
{% block cdnscript %}
{% endblock %}
{% block content %}
    <header class="container_satu_judul">
        <h1 class="sebuah_judul_artikel">
            {{ satu_artikel.judul }}
        </h1>
    </header>

    <div class="container_tanggal_sub">
        <p class="tanggal_sub">Ditulis oleh {{satu_artikel.penulis}} &nbsp; &nbsp; &nbsp; &nbsp; {{ satu_artikel.tanggal }} &nbsp; &nbsp; &nbsp; &nbsp; {{ satu_artikel.kategori }}</p>
    </div>
    <div class="container_isi_artikel">
        <div class="container_satu_gambar">
            <img class = "gambar_artikel_sub" src= "{{ satu_artikel.gambar_artikel.url }}" alt="">
        </div>

        <p class="isi_artikel_sub">
            {{ satu_artikel.isi_artikel }}
        </p>

    </div>
{% endblock %}

articles/templates/testing.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Static Example</title>
  <style>body {font-family: Arial, sans-serif;}</style>

</head>
<body>

  <input id="datepicker">
  {{ form.tanggal }}
  <script>
    $(function () {
      $("#datepicker").datepicker();
    });
  </script>


  <!-- jQuery -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

  <!-- Fengyuan Chen's Datepicker -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css" integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE=" crossorigin="anonymous" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js" integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k=" crossorigin="anonymous"></script>

</body>
</html>